
permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : C++ML
tagline: Visualy represent C++
author :
  name : C++ML Team
  email : contact@cplusplus.org
  github : CplusplusML
  twitter : cplusplusml

production_url : http://cplusplusml.github.com

google_analytics :
  tracking_id : 'UA-33465345-1'

facebook_comments:
  appid : 227519727381046
  num_posts: 5
  width: 580
  colorscheme: light

